version: '3'

services:

  db:
    container_name: SignalR-Chat.Db
    image: mcr.microsoft.com/mssql/server:2019-latest    
    ports:
      - "1433:1433"   
    environment:
      SA_PASSWORD: "Pass123*"
      ACCEPT_EULA: "Y"
